language: node_js
node_js:
 — "7"
script:
 — echo "Deploying!"
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project test-2c3bd — token 1/FhMDu_WC_vpOF3EA24udlQwKC9ACKRD9ymhFjUIepSI